# Generated by Django 3.0.4 on 2020-03-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200320_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=100, verbose_name='포인트'),
        ),
    ]
