# Generated by Django 3.0.4 on 2020-03-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ontrade',
            field=models.BooleanField(default=False, verbose_name='거래여부'),
        ),
    ]
