# Generated by Django 3.0.4 on 2020-03-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_ontrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(default=None, max_length=100, verbose_name='등록자'),
        ),
    ]
