# Generated by Django 3.0.4 on 2020-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_uploadfilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_name',
            field=models.CharField(default=None, max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='제품사진'),
        ),
    ]
