# Generated by Django 3.0.4 on 2020-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200329_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
