# Generated by Django 3.0.4 on 2020-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200329_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.CharField(default='', max_length=100, verbose_name='등록자'),
        ),
    ]
