# Generated by Django 3.0.4 on 2020-03-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200329_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='배송여부'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='explain',
            field=models.TextField(blank=True, verbose_name='제품설명'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='inputmoney',
            field=models.BooleanField(default=False, verbose_name='입금여부'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='material_name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='ontrade',
            field=models.BooleanField(default=False, verbose_name='거래여부'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='user_id',
            field=models.CharField(default='', max_length=100, verbose_name='등록자'),
        ),
    ]
