# Generated by Django 3.0.4 on 2020-03-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200329_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='번호')),
                ('account', models.IntegerField(default=0, verbose_name='계좌')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='trader_id',
            field=models.CharField(default='', max_length=100, verbose_name='거래자'),
        ),
    ]
