# Generated by Django 3.0.4 on 2020-03-31 02:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200330_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(default='', max_length=100, verbose_name='받을 사람')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None)),
                ('addressnum', models.TextField(verbose_name='우편번호')),
                ('address', models.TextField(verbose_name='주소')),
                ('detailaddress', models.TextField(verbose_name='상세주소')),
                ('addition', models.TextField(verbose_name='참고목록')),
                ('request', models.TextField(verbose_name='주의 사항')),
            ],
        ),
    ]
