# Generated by Django 3.0.4 on 2020-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200331_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='addition',
            field=models.TextField(blank=True, null=True, verbose_name='참고목록'),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='info',
            name='addressnum',
            field=models.TextField(blank=True, null=True, verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='info',
            name='detailaddress',
            field=models.TextField(blank=True, null=True, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='info',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='받을 사람'),
        ),
        migrations.AlterField(
            model_name='info',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name='주의 사항'),
        ),
    ]
