# Generated by Django 3.0.4 on 2020-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='num',
            field=models.IntegerField(default=0, verbose_name='번호'),
        ),
    ]
