# Generated by Django 3.0.4 on 2020-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_info_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/%H/%M/%S/%f'),
        ),
    ]
