# Generated by Django 3.0.4 on 2020-03-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200401_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='filename',
            field=models.CharField(default='', max_length=100, verbose_name='파일명'),
        ),
    ]
