# Generated by Django 3.0.4 on 2020-04-02 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200401_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='trade_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='거래 시작일'),
        ),
    ]
