# Generated by Django 3.0.4 on 2020-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_uploadfilemodel_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='success',
            field=models.BooleanField(default=True, verbose_name='거래 성사여부'),
        ),
    ]
