# Generated by Django 3.0.4 on 2020-04-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200402_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='explain',
            field=models.CharField(default='', max_length=400, verbose_name='제품설명'),
        ),
    ]
